### ISSUE TITLE
Update API endpoint

### ISSUE THREAD

**Issue by RoyalTS** [ZeevG/python-forecast.io#46] opened 2016-09-20 14:47 UTC
As per [today's announcement](http://status.darksky.net/2016/09/20/forecast-api-is-now-dark-sky-api.html):

> The API endpoint has changed from https://api.forecast.io/ to https://api.darksky.net/. The previous endpoint will continue to work for the foreseeable future, but please change your software as soon as possible.

**Comment by fabaff** [comment] 2016-09-26 20:09
Would be nice of you create a new release and publish it at PyPI.

Thanks

**Comment by blocke** [comment] 2016-09-30 02:49
HTTPS on api.forecast.io is currently presenting a certificate for "CN=darksky.net" and this module is now broken.

**Comment by BrianMitchL** [comment] 2016-09-30 03:14
I'm getting the same error, though referencing a different like in `_ssl.c`:
`requests.exceptions.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:645)`

Based on the error, it seems that it's `requests` or OpenSSL related.

I'm running my code on the `python:3` [docker image](https://hub.docker.com/_/python/). It seems strange for this (`python-forecast.io`) to suddenly stop working. @blocke, what is your environment like?

**Comment by ZeevG** [comment] 2016-09-30 04:06
Interesting... I ran some tests on Travis to try and reproduce the problem. I ran this commit 1faf779f...  which should be the same as the current 1.3.4 version and the [tests didn't fail](https://travis-ci.org/ZeevG/python-forecast.io/jobs/70686203) (for SSL reasons). The current master branch is [also passing](https://travis-ci.org/ZeevG/python-forecast.io).

I'll try to get a release out soon but it could still be 24 hours or so... and I'm not sure it will necessarily fix the problem.

Could it be a similar problem to this one https://github.com/kennethreitz/requests/issues/3593 ?

**Comment by BrianMitchL** [comment] 2016-09-30 04:17
I should note that I am using v1.3.4 with a manual URL pointing to the newer `api.darksky.net`. I don't think that should matter though. 

Because it worked fine on this version before today, and nothing has changed I wonder if darksky has changed certs or something has expired causing SSL in requests to fail.

I don't _think_ that this is related to that issue, but I could be wrong, I'm not an expert on SSL/TLS.

**Comment by BrianMitchL** [comment] 2016-10-01 02:51
All issues from yesterday seem to be gone. I'm assuming it was an issue with api.darksky.net or something between it and my server.

**Comment by ZeevG** [comment] 2016-10-03 10:29
I've released 1.3.5 which included the switch to api.darksky.net. I'm going to close this issue but feel free to reopen it if the problem comes back.

**Closed by ZeevG** 2016-10-03 10:29 UTC
